######################################################################
# Automatically generated by qmake (2.01a) sab gen 6 19:05:37 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MatInput.h ../matrix.h ../basx.h ../basxMath.h ../square_matrix.h
SOURCES += main.cpp MatInput.cpp ../basx.cpp ../basxMath.cpp
